//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YaYoBEgStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YaYoBEgUserDetail
    {
        public int UserDetailId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber_Cell { get; set; }
        public string PhoneNumber_Home { get; set; }
        public string Description { get; set; }
    
        public virtual YaYoBEgUser YaYoBEgUser { get; set; }
    }
}
