//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YaYoBEgStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YaYoBEgUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YaYoBEgUser()
        {
            this.YaYoBEgUserDetails = new HashSet<YaYoBEgUserDetail>();
        }
    
        public string Username { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        public Nullable<int> UserRolesId { get; set; }
        public int Id { get; set; }
    
        public virtual YaYoBEgUserRole YaYoBEgUserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YaYoBEgUserDetail> YaYoBEgUserDetails { get; set; }
    }
}
