//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YaYoBEgStudent.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YaYoBEgEntities : DbContext
    {
        public YaYoBEgEntities()
            : base("name=YaYoBEgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<YaYoBEgUserRole> YaYoBEgUserRoles { get; set; }
        public virtual DbSet<YaYoBEgUser> YaYoBEgUsers { get; set; }
        public virtual DbSet<YaYoBEgUserDetail> YaYoBEgUserDetails { get; set; }
    }
}
